### ISSUE TITLE
Icon not changed on reinjecting H&S

### ISSUE THREAD

**Issue by Boured** [d0k3/Universal-Inject-Generator#11]
Hello, I injected FBI into H&S and installed the CIA of FBI. After reinjecting the original H&S. I noticed that the home screen icon says it's still FBI.

Is this a problem?

**Comment by Boured** [comment]
And yes, H&S does launch, but the homescreen Icon still says it's FBI

**Comment by Boured** [comment]
I managed to fix it by deleting the extdata folder in Nintendo 3DS folder on my SD card. But this may make noobs panic so perhaps find a way to fix it. Or perhaps it's decrypt9? I don't know :/

**Comment by d0k3** [comment]
Nope, this is not UIG or Decrypt9. This is Nintendos own homemenu being slow at times, which we can't fix. Deleting that extdata folder is the only option to do it. Closing this now.
