### ISSUE TITLE
Possible mistake in process.sh

### ISSUE THREAD

**Issue by FredrIQ** [d0k3/Universal-Inject-Generator#19]
Offending part:
    printf "[+] IDENTIFY FILES TO WORK WITH\n"
    mv work work_old
    rm -rf work_old

**Comment by pixel-stuck** [comment]
This is intended behaviour... I suppose we could just do "rm -rf work" there, but this will still work fine (we want to remove the old work directory since its files could conflict with the process)

**Comment by FredrIQ** [comment]
Right, I understand the intention of the removal, but it seems like the mv there was done to allow backing up an existing work folder, which is rendered moot by the following rm. Hence why I brought this up, it looks a bit odd the way it is done now, even though it still _works_.

**Comment by pixel-stuck** [comment]
This stemmed from the original windows script, which I ported over to a shell script... It probably would just be best to rm -rf it in place
