### ISSUE TITLE
Stuck need help please

### ISSUE THREAD

**Issue by hamby0311l** [d0k3/Universal-Inject-Generator#9]
Hello, My name is mike. I have followed plailects guide to the T. I am currently in part 4(getting the OTP) and i have run into an issue. I cannot seem to find the solution anywhere so I was hoping maybe you could help. I have gotten down to step 14. I took the HS.app and fbi.cia and placed them into the input folder. once i double click on go, all i get is a bunch of failed notices and then it makes the "FBI_inject_with_banner.app" with 0 bytes of data. I am getting this error "warning, could not read common key", as well as "error:unknown file type" any help would be appreciated thank you.

**Comment by d0k3** [comment]
Better to discuss this on GBAtemp, so I'm closing this here.
